#+TITLE: Εργαστηριακή Άσκηση 2
#+SUBTITLE: Διαιρέτης Τάσης-Ρεύματος
#+AUTHOR: Τοροσιάν Νικόλας ΤΜ6220

* Circuit 1

+ Voltage divider circuit
  Potentiometer \(1k\Omega\)
** Ερωτήματα Άσκησης 1
*** Ερώτημα 1
1) ΠΡΟΣΟΧΗ: Αρχικά φροντίστε ο δείκτης του ποτενσιόμετρου να είναι περίπου στο μέσον της
περιστροφικής διαδρομής. Ακολούθως, Ρυθμίστε την μεταβλητή αντίσταση του 2.2ΚΩ ώστε το βολτόμετρο
να δείχνει 5V και μετρήστε το ρεύμα Ιολ και τις αντιστάσεις R1 , R2.

+ Μετρήσεις πειράματος Εργαστηρίου
  | V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
  |-------+--------+--------+--------|
  |     5 |   4.26 |   1100 |   1100 |

+ Μετρήσεις TinkerCad
  | V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
  |-------+--------+--------+--------|
  |     5 |   4.26 |   1100 |   1100 |


Από τα δεδομένα της εκφωνησης έχουμε ότι :
\begin{equation}
\begin{align}
\left{ V_{R_{2}} &= V_{total} \times \frac{R_{2}}{R_{1}+R_{2}},
&V_{R_{2}} &= \frac{V_{total}}{2} \right} \Rightarrow \\
&2 \times R_{2} = R_{1} + R_{2} \Rightarrow \\
&R_{1} = R_{2} = \frac{R_{tot}}{2} =1100 \left[\Omega\right] \\
\end{align}
\end{equation}

Ξέρουμε όμως ότι το συνολικό ρεύμα που διαρρέει το κύκλωμα δίνεται από τον νόμο του Ωμ ως εξής :

\begin{equation}
\begin{align}
I_{tot} &= \frac{V_{tot}}{R_{tot}} \\
&= \frac{10 \left[V\right]}{2200 \left[\Omega\right]} = 4.54 \times 10^{-3} \left[A\right]
\end{align}
\end{equation}

+ Μετρήσεις θεωριτικής επίλυσης πειράματος
  | V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
  |-------+--------+--------+--------|
  |     5 |   4.54 |   1100 |   1100 |

*** Ερώτημα 2
2) Συνδέστε μια αντίσταση 470 Ω (στο εργαστήριο χρησιμοποιήθηκε αντίσταση 1ΚΩ εδώ), παράλληλα προς την R2 σημεία (Β,Γ). Παρατηρήστε και σημειώστε τις τιμές
ρεύματος και τάσης (ενδείξεις αμπερομέτρου και βολτομέτρου).

\begin{equation}
\begin{align}
R_{eq} &= \frac{R_{2} \cdot R_{l}}{R_{2} + R_{l}} \, and,
&R_{tot} &= R_{1}+R_{eq} \\
R_{eq} &= \left( \frac{1,1 \times 1}{1,1 + 1} \right) k\Omega =523,7 \left[\Omega\right] \, and,
&R_{tot} &=(\left 1 + 0,523 \right) k\Omega = 1,523 \left[ k\Omega \right]\\
\end{align}
\end{equation}

Επομένως το ολικό ρεύμα που διαρρέει το κύκλωμα θα είναι :

\begin{equation}
\begin{align}
I_{tot} = \frac{V_{in}}{R_{tot}} = \frac{10 \left[V \right]}{1523 \left[\Omega \right]} \approx 6,5 \times 10^{-3} \left[A\right]
\end{align}
\end{equation}

Λόγω παραλληλίας των αντιστάσεων το ρεύμα διακλαδώνεται σε 2 ίσα ρεύματα Ι2 και Ιload. Επομένως η τιμές αυτών θα είναι :

\begin{equation}
\begin{align}
&I_{2}=I_{l}= \frac{I_{tot}}{2} = 3,24 \times 10^{-3} \left[A\right] \\
& V_{R_{2}} = I_{2} \times R_{2} = 3,24 \times 10^{-3} \left[A\right] \cdot 1100 \left[\Omega\right] = 3,55 \left[V\right]
\end{align}
\end{equation}

+ Μετρήσεις θεωριτικής επίλυσης κυκλώματος
  | V [V] | V(R2) | I [mA] | R1 [Ω] | R2 [Ω] | Rl [Ω] | Req [Ω] |
  |-------+-------+--------+--------+--------+--------+---------|
  |    10 |  3.55 |    6.5 |   1100 |   1100 |   1000 |    1523 |

+ Μετρήσεις TinkerCad
  | V [V] | V(R2) | I [mA] | R1 [Ω] | R2 [Ω] | Rl [Ω] | Req [Ω] |
  |-------+-------+--------+--------+--------+--------+---------|
  |    10 |  3.23 |   6.16 |   1100 |   1100 |   1000 |    1523 |

+ Μετρήσεις πειράματος Εργαστηριού
  | V [V] | V(R2) | I [mA] | R1 [Ω] | R2 [Ω] | Rl [Ω] | Req [Ω] |
  |-------+-------+--------+--------+--------+--------+---------|
  |    10 |       |        |   1100 |   1100 |   1000 |    1523 |

*** Ερώτημα 3
3) Μεταβάλλετε την μεσαία λήψη της μεταβλητής αντίστασης ώστε το βολτόμετρο να δείξει ξανά 5V.
Μετρήστε την τιμή των R1 , R2 αντίστοιχα και καταγράψτε την τιμή του ρεύματος από το αμπερόμετρο.

+ Μετρήσεις θεωριτικής επίλυσης κυκλώματος
  | V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
  |-------+--------+--------+--------|
  |       |        |        |        |

+ Μετρήσεις TinkerCad
  | V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
  |-------+--------+--------+--------|
  |       |        |        |        |

+ Μετρήσεις πειράματος Εργαστηριού
  | V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
  |-------+--------+--------+--------|
  |       |        |        |        |

*** Ερώτημα 4
4) Συγκρίνετε τις τιμές των ερωτημάτων Α , Β, Γ, και αναφέρετε τα συμπεράσματα σας.

+ Μετρήσεις θεωριτικής επίλυσης κυκλώματος
  | V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
  |-------+--------+--------+--------|
  |       |        |        |        |

+ Μετρήσεις TinkerCad
  | V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
  |-------+--------+--------+--------|
  |       |        |        |        |

+ Μετρήσεις πειράματος Εργαστηριού
  | V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
  |-------+--------+--------+--------|
  |       |        |        |        |


*** Ερώτημα 5
5) Αφαιρέστε την αντίσταση των 470 Ω και ρυθμίστε ξανά την R2 ώστε το βολτόμετρο να δείξει 5V. Συνδέστε
παράλληλα προς την R2 αντίσταση 560 ΚΩ και μετρήστε την τιμή της τάσης του βολτομέτρου.

+ Μετρήσεις θεωριτικής επίλυσης κυκλώματος
  | V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
  |-------+--------+--------+--------|
  |       |        |        |        |

+ Μετρήσεις TinkerCad
  | V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
  |-------+--------+--------+--------|
  |       |        |        |        |

+ Μετρήσεις πειράματος Εργαστηριού
  | V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
  |-------+--------+--------+--------|
  |       |        |        |        |


*** Ερώτημα 6
6) Γράψτε και δικαιολογήστε τις παρατηρήσεις σας σχετικά με το τί συμβαίνει όταν συνδέουμε μια μικρή
(470Ω) ή μία μεγάλη (560ΚΩ) αντίσταση παράλληλα στην R2

+ Μετρήσεις θεωριτικής επίλυσης κυκλώματος
  | V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
  |-------+--------+--------+--------|
  |       |        |        |        |

+ Μετρήσεις TinkerCad
  | V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
  |-------+--------+--------+--------|
  |       |        |        |        |

+ Μετρήσεις πειράματος Εργαστηριού
  | V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
  |-------+--------+--------+--------|
  |       |        |        |        |

** Δεδομένα ασκησης

Μετρήσεις πειράματος Εργαστήριο

| V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
|-------+--------+--------+--------|
|       |        |        |        |



| Ποτενσιόμετρο | 2,2 ΚΩ  |
| Πηγή τάσης    | 10 Βόλτ |
|               |         |

* Circuit 2

*** Ερώτημα 1
1) Πραγματοποιήστε το παρακάτω κύκλωμα:
Ακολούθως υπολογίστε το ρεύμα Ιολ και επαληθεύστε τον υπολογισμό σας με την βοήθεια ενός
αμπερομέτρου.
*** Ερώτημα 2
2) Υπολογίστε ποια θα πρέπει να είναι η τιμή μιας δεύτερης αντίστασης πού θα συνδεθεί παράλληλα με την
R1 ώστε το ρεύμα Ιολ να διπλασιαστεί. Ακολούθως συνδέστε την υπολογισθείσα αντίσταση και μετρήστε το
ρεύμα Ιολ του νέου κυκλώματος.
Συμφωνεί η μέτρηση σας με την υπολογισθείσα τιμή;
*** Ερώτημα 3
3) 3.1)Αρχικά πραγματοποιείστε το κύκλωμα του παρακάτω σχήματος χωρίς την RL , μετρήστε το Ι ολ και
υπολογίστε το Rολ του κυκλώματος.
   3.2) Προσθέσετε παράλληλα προς τις R1 , R2 , την αντίσταση RL =1ΜΩ, μετρήστε και καταγράψτε το ρεύμα Ιολ .
Ακολούθως υπολογίστε την Rολ του κυκλώματος. Πόσο άλλαξε η τιμή της Rολ από την περίπτωση (α);
   3.3) Αφαιρέσετε την RL = 1ΜΩ, και αντικαταστήσετε την με R= 1ΚΩ μετρήστε το Ιολ και υπολογίστε το Rολ .
Πόσο άλλαξε η τιμή της Rολ από την περίπτωση (α);
*** Ερώτημα 4
4) Συγκρίνετε τις μετρήσεις των ερωτημάτων Γ (α), με τις μετρήσεις των ερωτημάτων Γ (β), και γράψτε
τα συμπεράσματα σας.

+ Current divider circuit
