#+TITLE: Εργαστηριακή Άσκηση 2
#+SUBTITLE: Διαιρέτης Τάσης-Ρεύματος
#+AUTHOR: Τοροσιάν Νικόλας ΤΜ6220

* Circuit 1

+ Voltage divider circuit
  Potentiometer \(1k\Omega\)
** Ερωτήματα Άσκησης 1
*** Ερώτημα 1
1) ΠΡΟΣΟΧΗ: Αρχικά φροντίστε ο δείκτης του ποτενσιόμετρου να είναι περίπου στο μέσον της
περιστροφικής διαδρομής. Ακολούθως, Ρυθμίστε την μεταβλητή αντίσταση του 1ΚΩ ώστε το βολτόμετρο
να δείχνει 5V και μετρήστε το ρεύμα Ιολ και τις αντιστάσεις R1 , R2.

Μετρήσεις πειράματος Εργαστήριο
| V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
|-------+--------+--------+--------|
|     5 |        | 0.5R   | 0.5R   |

*** Ερώτημα 2
2) Συνδέστε μια αντίσταση 470 Ω, παράλληλα προς την R2 σημεία (Β,Γ). Παρατηρήστε και σημειώστε τις τιμές
ρεύματος και τάσης (ενδείξεις αμπερομέτρου και βολτομέτρου).

Μετρήσεις πειράματος Εργαστήριο

| V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
|-------+--------+--------+--------|
|       |        |        |        |

*** Ερώτημα 3
3) Μεταβάλλετε την μεσαία λήψη της μεταβλητής αντίστασης ώστε το βολτόμετρο να δείξει ξανά 5V.
Μετρήστε την τιμή των R1 , R2 αντίστοιχα και καταγράψτε την τιμή του ρεύματος από το αμπερόμετρο.

Μετρήσεις πειράματος Εργαστήριο

| V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
|-------+--------+--------+--------|
|       |        |        |        |

*** Ερώτημα 4
4) Συγκρίνετε τις τιμές των ερωτημάτων Α , Β, Γ, και αναφέρετε τα συμπεράσματα σας.

Μετρήσεις πειράματος Εργαστήριο

| V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
|-------+--------+--------+--------|
|       |        |        |        |

*** Ερώτημα 5
5) Αφαιρέστε την αντίσταση των 470 Ω και ρυθμίστε ξανά την R2 ώστε το βολτόμετρο να δείξει 5V. Συνδέστε
παράλληλα προς την R2 αντίσταση 560 ΚΩ και μετρήστε την τιμή της τάσης του βολτομέτρου.

Μετρήσεις πειράματος Εργαστήριο

| V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
|-------+--------+--------+--------|
|       |        |        |        |

*** Ερώτημα 6
6) Γράψτε και δικαιολογήστε τις παρατηρήσεις σας σχετικά με το τί συμβαίνει όταν συνδέουμε μια μικρή
(470Ω) ή μία μεγάλη (560ΚΩ) αντίσταση παράλληλα στην R2

Μετρήσεις πειράματος Εργαστήριο

| V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
|-------+--------+--------+--------|
|       |        |        |        |

** Δεδομένα ασκησης

Μετρήσεις πειράματος Εργαστήριο

| V [V] | I [mA] | R1 [Ω] | R2 [Ω] |
|-------+--------+--------+--------|
|       |        |        |        |



| Ποτενσιόμετρο | 2,2 ΚΩ  |
| Πηγή τάσης    | 10 Βόλτ |
|               |         |

* Circuit 2

*** Ερώτημα 1
1) Πραγματοποιήστε το παρακάτω κύκλωμα:
Ακολούθως υπολογίστε το ρεύμα Ιολ και επαληθεύστε τον υπολογισμό σας με την βοήθεια ενός
αμπερομέτρου.
*** Ερώτημα 2
2) Υπολογίστε ποια θα πρέπει να είναι η τιμή μιας δεύτερης αντίστασης πού θα συνδεθεί παράλληλα με την
R1 ώστε το ρεύμα Ιολ να διπλασιαστεί. Ακολούθως συνδέστε την υπολογισθείσα αντίσταση και μετρήστε το
ρεύμα Ιολ του νέου κυκλώματος.
Συμφωνεί η μέτρηση σας με την υπολογισθείσα τιμή;
*** Ερώτημα 3
3) 3.1)Αρχικά πραγματοποιείστε το κύκλωμα του παρακάτω σχήματος χωρίς την RL , μετρήστε το Ι ολ και
υπολογίστε το Rολ του κυκλώματος.
   3.2) Προσθέσετε παράλληλα προς τις R1 , R2 , την αντίσταση RL =1ΜΩ, μετρήστε και καταγράψτε το ρεύμα Ιολ .
Ακολούθως υπολογίστε την Rολ του κυκλώματος. Πόσο άλλαξε η τιμή της Rολ από την περίπτωση (α);
   3.3) Αφαιρέσετε την RL = 1ΜΩ, και αντικαταστήσετε την με R= 1ΚΩ μετρήστε το Ιολ και υπολογίστε το Rολ .
Πόσο άλλαξε η τιμή της Rολ από την περίπτωση (α);
*** Ερώτημα 4
4) Συγκρίνετε τις μετρήσεις των ερωτημάτων Γ (α), με τις μετρήσεις των ερωτημάτων Γ (β), και γράψτε
τα συμπεράσματα σας.

+ Current divider circuit
