#+title: AC Current measurements
#+subtitle: AC Current measurements
#+author: Torosian Nikolas

* ΑΣΚΗΣΗ 1
** EX_1
Δίδεται το παρακάτω κύκλωμα. Συνδέσετε την γεννήτρια στην είσοδο και ρυθμίσετε την για πλάτος
σήματος 10volt 𝑽𝒑"𝒑 και συχνότητας 1.5KΗz. Μετρήσετε με τον παλμογράφο το πλάτος του σήματος
εισόδου, όπως επίσης το πλάτος του σήματος στις αντιστάσεις 𝑹1, , 𝑹2, , 𝑹3 , 𝑹4 και 𝑹5 στην
συμπληρώσετε τους παρακάτω πίνακες και σχεδιάσετε σε μιλιμετρέ χαρτί τις κυματομορφές εισόδου και
όλων των τάσεων των αντιστάσεων στο ίδιο σύστημα ορθογωνίων αξόνων. Να σχεδιάσετε μια μόνο
περίοδο.

| V (p-p) | [Volt] |
|---------+--------|
| VR1     |        |
| VR2     |        |
| VR3     |        |
| VR4     |        |
| VR5     |        |

| V (rms) | [Volt] |
|---------+--------|
| VR1     |        |
| VR2     |        |
| VR3     |        |
| VR4     |        |
| VR5     |        |

| I (rms) | [Amp] |
|---------+-------|
| IR1     |       |
| IR2     |       |
| IR3     |       |
| IR4     |       |
| IR5     |       |
* ΑΣΚΗΣΗ 2
** EX_2
Δίδεται το παρακάτω κύκλωμα. Συνδέσετε την γεννήτρια στην είσοδο του κυκλώματος και ρυθμίσετε για
πλάτος σήματος 10volt 𝑉(p-p) και συχνότητα 2 ΚΗz. Μετρήσετε με τον παλμογράφο το πλάτος του σήματος
στις αντιστάσεις και σχεδιάσετε σε μιλιμετρέ χαρτί τις κυματομορφές εισόδου και των αντιστάσεων.
Σχεδιάσετε μία περίοδο και στο ίδιο σύστημα αξόνων. Συμπληρώσετε τους πίνακες


| V (p-p) | [Volt] |
|---------+--------|
| VR1     |        |
| VR2     |        |
| VR3     |        |
| VR4     |        |
| VR5     |        |

| V (rms) | [Volt] |
|---------+--------|
| VR1     |        |
| VR2     |        |
| VR3     |        |
| VR4     |        |
| VR5     |        |

| I (rms) | [Amp] |
|---------+-------|
| IR1     |       |
| IR2     |       |
| IR3     |       |
| IR4     |       |
| IR5     |       |
